name: Build & Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  windows:
    # Name the Job
    name: Windows Build & Test
    # Set the type of machine to run on
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1
      - name: List working directory
        run: dir
      - name: Test
        run: .\test.bat

  linux-gcc:
    # Name the Job
    name: Linux (GCC) Build & Test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List working directory
        run: ls -l
      - name: Test
        run: CC=gcc ./test.sh

  linux-clang:
    # Name the Job
    name: Linux (Clang) Build & Test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List working directory
        run: ls -l
      - name: Test
        run: CC=clang ./test.sh
