name: Build & Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-and-test:
    # Name the Job
    name: Build & Test
    # Set the type of machine to run on
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1
      - name: List working directory
        run: dir
      - name: Test
        run: .\test.bat
